_name_: akita_benchmark
dataset_name: akita_benchmark
dest_path: null
max_length: 10240
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
akita_benchmark:
  train_len: 102400
  classes: 1

